### ISSUE TITLE
Disabling JEI doesn’t disable JEI

### ISSUE THREAD

**Issue by V972** [Hipposgrumm/armor-trims#30]
Forge: 40.2.10
Jei: 1.18.2-9.7.2.1001
Armor Trims: 1.18.2-1.3.2

[debug.log](https://github.com/Hipposgrumm/armor-trims/files/12324300/debug.log)
[latest.log](https://github.com/Hipposgrumm/armor-trims/files/12324301/latest.log)

**Comment by Hipposgrumm** [comment]
Finally, an issue that is unique to a specific version.

**Comment by Hipposgrumm** [comment]
Or maybe it's not version-unique...

**Comment by Hipposgrumm** [comment]
Disable the option EnableQuickMaterials, it seems to be broken.

**Comment by Hipposgrumm** [comment]
Send me your config file, I wanna try to reproduce this myself to fix it.

**Comment by Hipposgrumm** [comment]
I released a new patch so this is hopefully no longer an issue.

**Comment by V972** [comment]
I...don' think it got fixed :(

The world joining stops during this line
<img width="608" alt="image" src="https://github.com/Hipposgrumm/armor-trims/assets/45125685/7b33a88d-5399-427e-8cd4-6b5f2a32d612">

and just hangs

I tries disabling JEI option, but it didn't help.

Here's my config: [armor_trims.toml.log](https://github.com/Hipposgrumm/armor-trims/files/12328360/armor_trims.toml.log)
(I added `.log` to the extention cause GitHub doesn't let uploading `.toml`)

**Comment by V972** [comment]
Tried downgrading JEI from 10.X to 9.X (some mods/addons are incompatible with it), didn't help.

**Comment by wabeb325** [comment]
With REI the game runs normally, but it gets stuck loading recipes and the disable function still doesn't work. There are no news of this issue, right? 😔

**Comment by Hipposgrumm** [comment]
REI works fine since there is no built in compact for it. 
I am also now back to work on Armor Trims Backport so this issue should be getting fixed.

**Comment by wabeb325** [comment]
What I meant by REI is that unlike JEI, REI does load, but this message pops up when you enter the menu and blocks REI functions.
![image](https://github.com/Hipposgrumm/armor-trims/assets/144356307/f497a3a6-41f3-4515-92ee-dd2a961e044b)

[rei.log](https://github.com/Hipposgrumm/armor-trims/files/13227025/rei.log)

**Comment by Hipposgrumm** [comment]
After having half rewritten how recipes are generated, hopefully this is fixed now.
Also I don’t know if the issue with disabling JEI was ever present but it’s fixed now.

**Comment by V972** [comment]
I don't see 1.3.4 on MD or CF and version newest 1.3.3 version still has the bug

**Comment by Hipposgrumm** [comment]
I only said the bug was fixed in the new version. I never said it was out yet.
